config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get 'search', to: 'pages#search'

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: "registrations"}
  get '/dashboard', to: 'pages#dashboard'
  get '/messages', to: 'pages#messages'

  resources :projects do
    resources :roles, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :roles, only: [] do
    resources :applications, only: [:create]
  end
  resources :applications, only: [:show]

  resources :users, only: [:new, :edit, :update, :create, :show, :destroy]

  resources :conversations do
    resources :messages, only: [:create]
  end

  get 'applications/:id/accept' => 'applications#accept_application', as: :accept_application
  get 'applications/:id/decline' => 'applications#decline_application', as: :decline_application

  resources :user_skills, only: [:edit, :update, :new, :create, :destroy]

  mount Attachinary::Engine => "/attachinary"

end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  attr_accessor :raw_address
  multisearchable against: [:skill_description, :first_name, :last_name, :city, :country]

  has_attachment :profile_photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, dependent: :destroy # This deletes the users projects when user is deleted.
  has_many :applications, through: :roles, dependent: :destroy # This deletes the users applications when user is deleted.
  has_many :roles, through: :projects
  has_many :applications

  has_many :user_skills
  has_many :skills, through: :user_skills

  has_many :conversations, class_name: 'Conversation', foreign_key: 'sender_id'
  has_many :conversations, class_name: 'Conversation', foreign_key: 'recipient_id'


   validates :email, presence: true, uniqueness: :true
   validates :first_name, presence: true
   validates :last_name, presence: true
   # validates :city, presence: true
   # validates :address, presence: true
   # validates :zip, presence: :true
   # validates :country, presence: :true


  # geocoded_by :full_address
  geocoded_by :city
  after_validation :geocode, if: :city_changed?


    # def full_address
    #   [country, city, address].compact.join(',')
    # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to user_path(@user)
  else
    render :new
  end
end

def edit

end


def update
  if @user.update(user_params)
    # raise
    redirect_to user_path(@user)
  else
    render :edit
  end
end

def show
  @skills = @user.skills

  @user_coordinates = { lat: @user.latitude, lng: @user.longitude }

end

def destroy
  @user.destroy
  redirect_to users_path
end

private

def set_user
  @user = User.find(params[:id])
  authorize @user
end

def user_params

  params.require(:user).permit(:first_name, :last_name, :email, :city, :zip, :country, :education, :profile_photo, :address, :address_line_2, :state, :skill_ids, :raw_address, :latitude, :longitude)
end

end

app/views/users/edit.html.erb
<div class="edit-wrapper">
  <div class="content-wrapper" style="background-color: #EEEEEE">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <br>
          <h1 class="text-center"><strong><em>Edit Profile</em></strong></h1>
          <hr>
          <%= simple_form_for(@user) do |f| %>
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <%= f.input :address %>
            <%= f.input :address_line_2 %>
            <%= f.input :city %>
            <%= f.input :state %>
            <%= f.input :zip %>
            <%= f.input :country %>
            <%= f.input :education %>
            <%= f.input :profile_photo, as: :attachinary %>
            <%= f.submit class: "btn btn-primary", style: "border:none; background-color: #2f3f59; margin-bottom: 25px;" %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.profile_photo %>
<% photo = cl_image_path @user.profile_photo.path %>
<% else %>
<% photo = image_path 'face_placeholder.png' %>
<% end %>

<div class="wrapper content-wrapper-footer" style="background-color: #EEEEEE">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <div class="profile-banner" style="margin-top: 20px;">
          <div class="user-img" style="background-image: url('<%= photo %>');">
          </div>
          <div class="user-info">
            <h1><%= @user.first_name %> <%= @user.last_name %></h1>
            <p><i class="fa fa-globe fa-fw"></i> <%= @user.city %>, <%= @user.country %> </p>
            <p><i class="fa fa-graduation-cap fa-fw"></i> <%= @user.education %></p>
          </div>
          <% if policy(@user).update? %>
          <%= link_to edit_user_path(@user), class: "edit-profile-btn" do %>
          <i class="fa fa-wrench"></i>
          <% end %>
          <% end %>

          <%= link_to edit_user_path(@user), class: "message-me-btn" do %>
          <span><i class="fa fa-envelope-o"></i>  Message</span>
          <% end %>

          <%= link_to new_user_skill_path, class: 'add-skill' do %>
          <i class="fa fa-plus-circle" style="font-size: 40px; margin-left: 190px; margin-bottom: -25px; color: white;"></i>
          <% end %>
        </div>
      </div>
    </div>

    <% @skills.each do |skill| %>
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <%= render "user_skills/card", skill: skill %>
      </div>
    </div>
    <% end %>
  </div>
</div>