config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get 'search', to: 'pages#search'

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: "registrations"}
  get '/dashboard', to: 'pages#dashboard'
  get '/messages', to: 'pages#messages'

  resources :projects do
    resources :roles, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :roles, only: [] do
    resources :applications, only: [:create]
  end
  resources :applications, only: [:show]

  resources :users, only: [:new, :edit, :update, :create, :show, :destroy]

  resources :conversations do
    resources :messages, only: [:create]
  end

  get 'applications/:id/accept' => 'applications#accept_application', as: :accept_application
  get 'applications/:id/decline' => 'applications#decline_application', as: :decline_application

  resources :user_skills, only: [:edit, :update, :new, :create, :destroy]

  mount Attachinary::Engine => "/attachinary"

end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill

  has_many :users
  has_many :skills

  validates :skill, presence: true
  validates :user_id, :uniqueness => {:scope => :skill_id}

end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
  before_action :set_user_skill, only: [:show, :edit, :update, :destroy]

  # def update
  #   user_skills = params[:user][:skill_ids].reject { |c| c.blank? }
  #   current_user.skills.destroy_all
  #   user_skills.each do |id|
  #     s = UserSkill.find(id.to_i)
  #     UserSkill.create(user: current_user, skill: s)
  #   end

  #   if @user.update(user_params)
  #     # raise
  #     redirect_to user_path(@user)
  #   else
  #     render :edit
  #   end
  # end
  def update
      @user_skill = UserSkill.find(params[:id])
      @user_skill.update(user_skill_params)
      authorize @user_skill
      redirect_to user_path(current_user)
  end

  def destroy
    @user_skill = UserSkill.find(params[:id])
    @user_skill.destroy
    authorize @user_skill
    redirect_to user_path(current_user)

  end

  def edit
  end

  def new
    @user_skill = UserSkill.new
    authorize @user_skill
  end

  def create
    @user_skill = UserSkill.new(user_skill_params)
    @user_skill.user = current_user
    authorize @user_skill
    if @user_skill.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def set_user_skill
    @user_skill = UserSkill.find(params[:id])
    authorize @user_skill
  end

  def user_skill_params
    params.require(:user_skill).permit(:years, :description, :skill_id)
  end
end

app/views/user_skills/_card.html.erb
<div class="skill-card flex">
  <div class="skill-card-left flex-column">
    <% if policy(@user).update? %>
      <h1><%= skill.skill %>
        <% user_skill = skill.user_skills.where(user: @user).first %>
        <%= link_to edit_user_skill_path(user_skill) do %>
          <i class="fa fa-pencil" aria-hidden="true" style="color: #acadaf"></i>
        <% end %>
      </h1>
    <% else %>
      <h1><%= skill.skill %></h1>
    <% end %>
    <h4>Years  <%= skill.user_skills.where(user_id: @user.id).first.years.to_i %></h4>
    <h6 style="text-decoration: underline; color: black">EXPERIENCE</h6>
    <p><%= skill.user_skills.where(user_id: @user.id)[0].description %></p>
  </div>

  <%= cl_image_tag skill.photo, width: 60, class: 'skill-photo' %>

  <!-- EDIT -->
  <div class="flex-end">

  </div>

</div>

app/views/user_skills/edit.html.erb
<div class="edit-wrapper" style="background: #f2f2f2">
  <div class="content-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <br>
          <h1 class="text-center"><strong><em>Edit <%= @user_skill.skill.skill %> Skills</em></strong></h1>
          <hr>
          <%= simple_form_for(@user_skill) do |f| %>
            <%= f.input :years, collection: (1..30).to_a %>
            <%= f.input :description, :as => :text %>
            <div class="text-left">
              <%= f.submit "Edit", class: "btn btn-primary" %>
            <% end %>
              <%= button_to "Delete", user_skill_path(@user_skill), method: :delete, class: "btn btn-warning"%>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/user_skills/new.html.erb
<div class="edit-wrapper" style="background: #304a75">
  <div class="content-wrapper" style="background-color: #EEEEEE">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <br>
          <h1 class="text-center"><strong><em>Add a new skill</em></strong></h1>
          <hr>
          <%= simple_form_for(@user_skill) do |f| %>
            <%= f.association :skill, include_blank: false, include_hidden: false, label_method: lambda { |skill| "#{skill.skill}" } %>
            <%= f.input :years, collection: (1..30).to_a %>
          <div class="button">
            <%= f.input :description, :as => :text %>
            <%= f.submit "Create", class: "btn btn-primary", style: "background-color: #2f3f59; border:none"  %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>