config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get 'search', to: 'pages#search'

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: "registrations"}
  get '/dashboard', to: 'pages#dashboard'
  get '/messages', to: 'pages#messages'

  resources :projects do
    resources :roles, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :roles, only: [] do
    resources :applications, only: [:create]
  end
  resources :applications, only: [:show]

  resources :users, only: [:new, :edit, :update, :create, :show, :destroy]

  resources :conversations do
    resources :messages, only: [:create]
  end

  get 'applications/:id/accept' => 'applications#accept_application', as: :accept_application
  get 'applications/:id/decline' => 'applications#decline_application', as: :decline_application

  resources :user_skills, only: [:edit, :update, :new, :create, :destroy]

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container" style="margin-bottom: none">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li>
            <%= link_to '#' do %>
              <i class="fa fa-linkedin"></i>
            <% end %>
          </li>
          <li>
            <%= link_to '#' do %>
              <i class="fa fa-twitter"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <p>This is a page for @StartShare</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <div>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag ("startshare_logo.png")%>
      <%= link_to t(".projects", default: "Projects"), projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Create Account"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Dashboard"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>

  </div>

  <!-- Left Navigation -->
  <div class="navbar-wagon-left hidden-xs hidden-sm">

  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.profile_photo %>
            <% photo = cl_image_path current_user.profile_photo.path %>
          <% else %>
            <% photo = image_path 'face_placeholder.png' %>
          <% end %>
          <div class="avatar dropdown-toggle" style="background-image: url('<%= photo %>');" id="navbar-wagon-menu" data-toggle="dropdown"></div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-tasks"></i>  Dashboard
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-cogs"></i> <%= t(".edit_user_registration_path", default: "Account Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
              <i class="fa fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Search form -->
    <%= form_tag search_path, method: "get", :class => 'navbar-wagon-search' do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: "navbar-wagon-search-input" %>
      <button class='navbar-wagon-search-btn'>
        <i class="fa fa-search"></i>
      </button>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>