config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get 'search', to: 'pages#search'

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: "registrations"}
  get '/dashboard', to: 'pages#dashboard'
  get '/messages', to: 'pages#messages'

  resources :projects do
    resources :roles, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :roles, only: [] do
    resources :applications, only: [:create]
  end
  resources :applications, only: [:show]

  resources :users, only: [:new, :edit, :update, :create, :show, :destroy]

  resources :conversations do
    resources :messages, only: [:create]
  end

  get 'applications/:id/accept' => 'applications#accept_application', as: :accept_application
  get 'applications/:id/decline' => 'applications#decline_application', as: :decline_application

  resources :user_skills, only: [:edit, :update, :new, :create, :destroy]

  mount Attachinary::Engine => "/attachinary"

end

app/models/project.rb
class Project < ApplicationRecord
  include PgSearch
  multisearchable against: [:name, :summary]

  has_attachment :photo

  belongs_to :user
  has_many :roles, dependent: :destroy

  validates :name, presence: true
  validates :summary, presence: true
  validates :details, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :stage, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @projects = policy_scope(Project).order(created_at: :desc)
  end

  def show
    @application = Application.new
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :located, :summary, :details, :start_date, :end_date, :stage, :photo)
  end

  def set_project
      @project = Project.find(params[:id])
      authorize @project
  end
end

app/views/projects/_card.html.erb
<% if project.photo %>
  <% photo = cl_image_path project.photo.path %>
<% else %>
  <% photo = image_path 'background.jpg' %>
<% end %>

<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= photo %>'); margin-top:5px;">
  <div class="card-category"></div>
    <div class="card-description">
      <h2><%= project.name %></h2>
      <p><%= project.summary %></p>
      <h4><%= project.located %></h4>
    </div>
  <%= link_to "", project_path(project), class: "card-link"  %>
</div>

app/views/projects/edit.html.erb
<div class="content-wrapper" style="background-color: #EEEEEE">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <h1 class="text-center" style="color: #595a5b;">Edit Project</h1>

        <%= simple_form_for(@project) do |f| %>
          <%= f.input :name %>
          <%= f.input :summary %>
          <%= f.input :details, :as => :text %>
          <%= f.input :located %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.input :stage %>
          <%= f.input :photo, as: :attachinary %>

        <div class="button-flex" style="margin-bottom: 14px;">
          <%= f.submit "Update", class: "btn btn-primary", style: "background-color: #2f3f59; border: none;" %>
        <% end %>
        <%= button_to "Delete", project_path(@project), method: :delete, class: "btn btn-warning", style: "background-color: #2f3f59; border: none;" %>
        </div>
     </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="content-wrapper" style="background-color: #EEEEEE;">
  <div class="container">
    <br>
    <h1 class="text-center" style="color: #595a5b">Available Projects</h1>
    <hr>
    <div class="row">
        <% @projects.each do |project| %>
          <div class="col-xs-12 col-sm-4">

              <%= render "projects/card", project: project %>

          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="content-wrapper">
  <div class="container" style="margin-top: 60px; margin-bottom: 40px;">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3" style="border-radius: 8px; padding: 8px; background-color: #D3D3D3">
        <h2><center>Project Details</center></h2>
        <hr>
        <%= simple_form_for(@project) do |f| %>
          <%= f.input :name %>
          <%= f.input :summary %>
          <%= f.input :details, :as => :text %>
          <%= f.input :located %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.input :stage %>
          <%= f.input :photo, as: :attachinary %>
          <%= f.submit :submit, class: "btn btn-primary", style: "background-color: #2f3f59; border:none;" %>
        <% end %>
     </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<!-- The links below are for OpenGraph and Twitter to be able to pull the relevent info when sharing on their sites. -->
<% if @project.photo %>
  <% img = cl_image_path @project.photo.path %>
<% else %>
  <% img = image_path 'background.jpg' %>
<% end %>
<% content_for :meta_title, @project.name %>
<% content_for :meta_description, @project.summary %>
<% content_for :meta_image, cloudinary_url(img) %>

  <% if @project.photo %>
  <% photo = cl_image_path @project.photo.path %>
<% else %>
<% photo = image_path 'background.jpg' %>
<% end %>

<% if @project.user.profile_photo %>
  <% profile = cl_image_path @project.user.profile_photo %>
<% else %>
  <% profile = image_path 'face_placeholder.png' %>
<% end %>
<div class="wrapper" style="background-color: #EEEEEE">
<div class="banner-show-project" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= photo %>');" >

  <% if @project.user == current_user %>
    <%= link_to edit_project_path(@project), class: "edit-project" do %>
      <i class="fa fa-wrench"></i>
    <% end %>
  <% end %>

  <% if @project.user == current_user %>
      <%= link_to dashboard_path, class: "edit-project-dashboard" do %>
        <i class="fa fa-tasks"></i>
    <% end %>
  <% end %>

  <div class="container">
    <h1><%= @project.name %></h1>
    <p style="color: white; font-weight: 300"><%= @project.summary %></p>
    <h4 style="color: white;"><%= @project.located %></h4>
    <i class="fa fa-calendar" aria-hidden="true" style="color:white; font-size: 25px;text-decoration-style: bold; margin-top: 25px;"> <%= @project.start_date %> </i>
  </div>

</div>

<br>

<div class="container" style="min-height: 100px; background-color: #f9fafc; margin-top: 10px; margin-bottom: 30px; border-radius: 5px; padding: 10px; box-shadow: 2px 2px 3px rgba(0,0,0,0.2)">
  <h3 style="margin-bottom: 20px;">What we're about</h3 style="margin-bottom: 20px;">
  <p><%= @project.details %></p>

</div>

<div class="container">
  <div class="roles-text">
    <h2 class="text-center" style="margin-bottom: 12px; color: #595a5b;">Available roles</h2>

    <% if @project.user == current_user %>
      <%= link_to new_project_role_path(@project) do %>
        <i class="fa fa-plus-circle" style="font-size: 40px; color: #2f3f59;"></i>
      <% end %>
    <% end %>
  </div>
    <% if @project.roles.empty? %>
      <p class="text-center"><%= "There are no roles available for this project" %></p>
    <% else %>
    <hr style="color: #2e3033">




      <% @project.roles.each do |role| %>

      <% if role.icon %>
        <% icon = cl_image_path role.icon.path %>
      <% else %>
        <% icon = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Infobox_info_icon.svg/1024px-Infobox_info_icon.svg.png' %>
      <% end %>
      <div class="project-role-card">
        <div class="project-role-card-icon avatar-large" style="background-image: url('<%= icon %>');">
        </div>
        <div class="project-role-card-content">
          <h3><%= role.name %></h3>
          <p><%= role.description %></p>
        </div>
        <div class="project-role-card-button">
          <% if @project.user == current_user %>
            <%= link_to "Edit", edit_project_role_path(@project, role), class: 'btn btn-primary' %>
          <% else %>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#application<%= role.id %>">
             Apply
            </button>
          <% end %>
        </div>
        <% unless role.applications.any? %>
          <div class="project-role-card-ribbon">
            <span>NEW</span>
          </div>
        <% end %>
      </div>

      <div class="modal fade" id="application<%= role.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="text-center modal-body" style="height: 350px;">
              <h2 class="modal-title" style="margin-bottom: 30px;">Apply to <%= role.name %></h2>
              <%= simple_form_for [role, @application] do |f| %>
              <%= f.input :cover_message, input_html: {rows: '6'} %>
              <div style="margin-top: 8px;"> <%= f.submit :Apply, class: "btn btn-primary" %> </div>
              <% end %>


            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
</div>
<!-- Modal -->